print("Calcul HT into TVA")
HT = float(input("Entrer un prix HT: "))
print("Le montant HT est: ", HT)
print("Saisir un taux de tva: ")
TVA = float(input("Entrer un taux de TVA: "))
print("Le taux de TVA est: ", TVA)
mTVA = ((TVA/100)*HT)
print("Montant de TVA: ", mTVA)
TTC = (HT+mTVA)
print("Total TTC: ", TTC)
